language: minimal

services: docker

install:
  - docker build -t omarradwan213/udagram-users-api .
  
before_deploy:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - mkdir -p ${HOME}/.kube
  - echo "$KUBE_CONFIG" | base64 --decode > ${HOME}/.kube/config
    
deploy:
  - provider: script
    script:
      - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
      - docker image push omarradwan213/udagram-users-api
    on:
      branch: master
  - provider: script
    script:
      - kubectl rollout restart deployment users-api
    on:
      branch: master